//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectVPN
    {
        public int ID { get; set; }
        public string projectname { get; set; }
        public string customername { get; set; }
        public string projectdetail { get; set; }
        public string projectowner { get; set; }
        public string currentsummary { get; set; }
        public string nextsteps { get; set; }
        public string status { get; set; }
    }
}
