//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ISW_Data_duplicate
    {
        public int ID { get; set; }
        public string CustomerName { get; set; }
        public string CategoryName { get; set; }
        public Nullable<System.DateTime> ScheduledDate { get; set; }
        public string ActivityName { get; set; }
        public Nullable<int> MigrationWindow { get; set; }
        public Nullable<int> MigrationGroup { get; set; }
        public Nullable<int> TotalUnits { get; set; }
        public Nullable<System.DateTime> MigrationDate { get; set; }
        public string SubStatus { get; set; }
        public string Review { get; set; }
        public string Status { get; set; }
        public string UserName { get; set; }
        public string UpdatedDate { get; set; }
        public Nullable<int> completed { get; set; }
        public Nullable<int> inprogress { get; set; }
        public Nullable<int> failed { get; set; }
        public Nullable<int> parent_id { get; set; }
        public string Exception { get; set; }
    }
}
